# authors: Valentin Oliver Loftsson <valentin.loftsson@hestia.ai>
PREFIX : <http://hestia.ai/>

SELECT ?advertiser ?type ?value
WHERE {
  ?x a :Criterion .
  ?x :advertiser ?advertiser .
  ?x :type ?type .
  ?x :value ?value
}
