PREFIX :   <http://schema.org/>
PREFIX ex: <http://www.example.com/>

SELECT ?date ?dislike ?like ?open ?number_of_match ?number_of_messages_received ?number_of_messages_sent ?number_of_superlike
WHERE {
    ?swipePass a ex:SwipePass .
    ?swipePass ex:date ?date .
    ?swipePass ex:value ?dislike .
    ?swipeLike a ex:SwipeLike .
    ?swipeLike ex:date ?date .
    ?swipeLike ex:value ?like .
    ?appOpen a ex:AppOpen .
    ?appOpen ex:date ?date .
    ?appOpen ex:value ?open .
    ?match a ex:match .
    ?match ex:date ?date .
    ?match ex:value ?number_of_match .
    ?message_received a ex:message_received .
    ?message_received ex:date ?date .
    ?message_received ex:value ?number_of_messages_received .
    ?message_sent a ex:message_sent .
    ?message_sent ex:date ?date .
    ?message_sent ex:value ?number_of_messages_sent .
    ?superlike a ex:superlike .
    ?superlike ex:date ?date .
    ?superlike ex:value ?number_of_superlike .
}
