PREFIX :   <http://schema.org/>
PREFIX ex: <http://www.example.com/>

SELECT ?date ?dislike ?like ?open
WHERE {
    ?swipePass a ex:SwipePass .
    ?swipePass ex:date ?date .
    ?swipePass ex:value ?dislike .
    ?swipeLike a ex:SwipeLike .
    ?swipeLike ex:date ?date .
    ?swipeLike ex:value ?like .
    ?appOpen a ex:AppOpen .
    ?appOpen ex:date ?date .
    ?appOpen ex:value ?open .
}
