PREFIX :   <http://schema.org/>
PREFIX ex: <http://www.example.com/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?date ?dislike ?like
WHERE {
    ?swipepass a ex:SwipePass .
    ?swipepass ex:date ?date .
    ?swipepass ex:value ?dislike .
    ?swipelike a ex:SwipeLike .
    ?swipelike ex:date ?date .
    ?swipelike ex:value ?like .
}
