# authors: Valentin Oliver Loftsson <valentin@hestia.ai>
PREFIX :  <http://hestia.ai/>

SELECT ?name ?hex
WHERE {
		?color :name ?name .
    ?color :hex ?hex .
    ?color :rgb ?rgb .
    FILTER(?rgb = "rgb(255, 3, 62)")
}
