# authors: Emmanuel Eckard <emmanuel@hestia.ai>
PREFIX ex: <http://www.example.com/>
PREFIX schema: <http://schema.org/>

SELECT ?name ?impressions ?engagements WHERE
{
  ?x a schema:Organization .
  ?x schema:name ?name .
  OPTIONAL
  {
    SELECT ?x (COUNT(?impression) AS ?impressions) WHERE
    {
      ?impression a ex:Impression .
      ?impression ex:Advertiser ?x .
    }
    GROUP BY ?x
  }
  OPTIONAL
  {
    SELECT ?x (COUNT(?engagement) AS ?engagements) WHERE
    {
      ?engagement a ex:Engagement .
      ?engagement ex:Advertiser ?x .
    }
    GROUP BY ?x
  }
}
