#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

DIRECTORY='/dev/tty'
if [ -d "$DIRECTORY" ]; then
  exec >/dev/tty 2>&1
fi

# https://scottsauber.com/2021/06/01/using-husky-git-hooks-and-lint-staged-with-nested-folders/
cd ./experiences && npm run pre-commit
