PREFIX h: <http://hestia.ai/>

SELECT ?app_name ?event_time ?event_id ?event_type WHERE
{
    ?event a h:off_facebook_activity .
    ?event h:app_name ?app_name .
    ?event h:timestamp ?event_time .
    ?event h:id ?event_id .
    ?event h:type ?event_type
}
