<template>
  <VContainer>
    <VRow>
      <VCol cols="12" md="6">
        <h3>General Information</h3>
        <VList>
          <VListItem v-for="item in items" :key="item.title">
            <VListItemContent>
              <div class="d-flex justify-space-between">
                <span v-text="item.title + ':'" />
                <div
                  v-if="Array.isArray(item.value)"
                  class="d-flex flex-column flex-md-row flex-wrap"
                >
                  <VChip v-for="l in item.value" :key="l" class="ma-2" label>
                    {{ l }}
                  </VChip>
                </div>
                <span v-else v-text="item.value" />
              </div>
            </VListItemContent>
            <VListItemIcon>
              <VTooltip
                v-if="item.hint"
                v-model="item.show"
                left
                max-width="200"
              >
                <template #activator="{ on, attrs }">
                  <VHover>
                    <VIcon color="" v-bind="attrs" v-on="on">
                      $vuetify.icons.mdiInformationOutline
                    </VIcon>
                  </VHover>
                </template>
                <span>{{ item.hint }}</span>
              </VTooltip>
            </VListItemIcon>
          </VListItem>
        </VList>
      </VCol>
    </VRow>
    <VRow>
      <VCol cols="12">
        <h3>Lists</h3>
      </VCol>
    </VRow>
    <VRow>
      <VCol
        v-for="table in tables"
        :key="table.title"
        cols="12"
        md="6"
        align="center"
      >
        <VCard max-width="" height="100%">
          <VCardTitle>
            {{ table.title }}
            <VSpacer />
            <VTooltip
              v-if="table.hint"
              v-model="table.show"
              left
              max-width="200"
            >
              <template #activator="{ on, attrs }">
                <VIcon color="" v-bind="attrs" v-on="on">
                  $vuetify.icons.mdiInformationOutline
                </VIcon>
              </template>
              <span>{{ table.hint }}</span>
            </VTooltip>
          </VCardTitle>
          <VCardText>
            <UnitFilterableTable
              v-bind="{ headers: table.headers, items: table.values }"
            />
          </VCardText>
        </VCard>
      </VCol>
    </VRow>
  </VContainer>
</template>

<script>
import mixin from './mixin'

export default {
  mixins: [mixin],
  data() {
    const [v] = this.values
    return {
      items: [
        {
          title: 'Gender',
          value: v.gender,
          hint: 'Gender associated with the account. This information may be inferred.'
        },
        {
          title: 'Age',
          value: JSON.parse(v.age),
          hint: 'Date of birth Twitter has inferred about the account and corresponding current age.'
        },
        {
          title: 'Languages',
          value: JSON.parse(v.languages).map(l => l.language),
          hint: 'Languages associated with the account. This information may be inferred.'
        },
        {
          title: 'numAudiences',
          value: v.numAudiences,
          hint: 'Number of tailored audiences (audiences generated by advertisers) the account is a part of.'
        }
      ],
      tables: [
        {
          title: 'Inferred Interests',
          headers: [{ text: 'Inferred Interests', value: 'interests' }],
          values: JSON.parse(v.interests).map((v) => {
            return { interests: v.name }
          }),
          hint: 'These are some of the interests that match you, based on your profile, your activity and the topics you follow. They are used to personalise your experience on Twitter, including the ads you see.'
        },
        {
          title: 'Lookalike Advertisers',
          headers: [
            { text: 'Lookalike Advertisers', value: 'lookalikeAdvertisers' }
          ],
          values: JSON.parse(v.lookalikeAdvertisers).map((v) => {
            return { lookalikeAdvertisers: v }
          }),
          hint: 'List of screen names for the advertisers that own the look-alike audiences your account is a part of.'
        },
        {
          title: 'Advertisers',
          headers: [{ text: 'Advertisers', value: 'advertisers' }],
          values: JSON.parse(v.advertisers).map((v) => {
            return { advertisers: v }
          }),
          hint: 'Here are the advertisers who have added you to one of their audiences. Custom audiences are often created from lists of email addresses or browsing behaviour. They allow advertisers to reach potential customers or users who have already expressed interest in their business.'
        },
        {
          title: 'Shows',
          headers: [{ text: 'Shows', value: 'shows' }],
          values: JSON.parse(v.shows).map((v) => {
            return { shows: v }
          }),
          hint: 'The programmes you are likely to watch, based on your account activity and information.'
        },
        {
          title: 'Location History',
          headers: [{ text: 'Location History', value: 'locationHistory' }],
          values: JSON.parse(v.locationHistory).map((v) => {
            return { locationHistory: v }
          }),
          hint: 'Here are the locations that Twitter has associated with your account, based on your activity from the last 60 days.'
        },
        {
          title: 'Partner Interests',
          headers: [{ text: 'Partner Interests', value: 'partnerInterests' }],
          values: JSON.parse(v.partnerInterests).map((v) => {
            return { partnerInterests: v }
          })
        }
      ],
      ...v
    }
  },
  methods: {
    drawViz() {}
  }
}
</script>
