# authors: Valentin Oliver Loftsson <valentin@hestia.ai>
PREFIX :  <http://schema.org/>

SELECT ?screenName ?name
WHERE {
    ?advertiser :alternateName ?screenName .
    ?advertiser :name ?name
}
ORDER BY ?screenName
