PREFIX :   <http://schema.org/>
PREFIX ex: <http://www.example.com/>

SELECT ?date ?Passes ?Likes
WHERE {
    ?swipePass a ex:SwipePass .
    ?swipePass ex:date ?date .
    ?swipePass ex:value ?Passes .
    ?swipeLike a ex:SwipeLike .
    ?swipeLike ex:date ?date .
    ?swipeLike ex:value ?Likes .
}
