# authors: Valentin Oliver Loftsson <valentin.loftsson@hestia.ai>
PREFIX : <http://hestia.ai/>

SELECT ?advertiser ?type ?value (count(?type) AS ?count)
WHERE {
  ?x :advertiser ?advertiser .
  ?x :type ?type .
  ?x :value ?value
}
GROUP BY ?advertiser ?type ?value
