PREFIX :   <http://schema.org/>
PREFIX ex: <http://www.example.com/>

SELECT ?date ?pass ?likes ?msg_rcv ?msg_sent
WHERE {
    ?appOpen a ex:AppOpen .
    ?appOpen ex:date ?date .
    OPTIONAL {
        ?swipePass a ex:SwipePass .
        ?swipePass ex:date ?date .
        ?swipePass ex:value ?pass .
    }
    OPTIONAL {
        ?swipeLike a ex:SwipeLike .
        ?swipeLike ex:date ?date .
        ?swipeLike ex:value ?likes .
    }
    OPTIONAL {
        ?message_received a ex:message_received .
        ?message_received ex:date ?date .
        ?message_received ex:value ?msg_rcv .
    }
    OPTIONAL {
        ?message_sent a ex:message_sent .
        ?message_sent ex:date ?date .
        ?message_sent ex:value ?msg_sent .
    }
}
