# authors: Florian Singer <florian.singer@hestia.ai>
PREFIX :  <http://schema.org/>

CONSTRUCT {
  ?advertiser a :Organization .
  ?advertiser :name ?name .
  ?advertiser :advertised ?person .
}
WHERE {
  ?advertiser a :Organization .
  ?advertiser :name ?name .
  ?person a :Person
}
