import {
  mdiAccount,
  mdiAccountGroup,
  mdiAlert,
  mdiAutorenew,
  mdiCached,
  mdiCalendar,
  mdiChartBar,
  mdiCheckboxBlankOutline,
  mdiCheckCircle,
  mdiChevronLeft,
  mdiClose,
  mdiCloseBox,
  mdiCloseCircle,
  mdiCog,
  mdiContentCopy,
  mdiDatabase,
  mdiDatabaseRemove,
  mdiDelete,
  mdiDownload,
  mdiExport,
  mdiFileSearch,
  mdiFileUpload,
  mdiFilter,
  mdiHome,
  mdiInformationOutline,
  mdiLockOpenVariant,
  mdiMagnify,
  mdiMinus,
  mdiMinusBox,
  mdiNumeric1CircleOutline,
  mdiNumeric2CircleOutline,
  mdiPlus,
  mdiTuneVariant,
  mdiSend,
  mdiShare,
  mdiStepForward,
  mdiTable,
  mdiTextBoxEditOutline,
  mdiTwitter,
  mdiFolderInformationOutline,
  mdiFileMultipleOutline
} from '@mdi/js'

export default {
  icons: {
    iconfont: 'mdiSvg',
    values: {
      mdiAccount,
      mdiAccountGroup,
      mdiAlert,
      mdiAutorenew,
      mdiCached,
      mdiCalendar,
      mdiChartBar,
      mdiCheckboxBlankOutline,
      mdiCheckCircle,
      mdiChevronLeft,
      mdiClose,
      mdiCloseBox,
      mdiCloseCircle,
      mdiCog,
      mdiContentCopy,
      mdiDatabase,
      mdiDatabaseRemove,
      mdiDelete,
      mdiDownload,
      mdiExport,
      mdiFileSearch,
      mdiFileUpload,
      mdiFilter,
      mdiHome,
      mdiInformationOutline,
      mdiLockOpenVariant,
      mdiMagnify,
      mdiMinus,
      mdiMinusBox,
      mdiNumeric1CircleOutline,
      mdiNumeric2CircleOutline,
      mdiPlus,
      mdiTuneVariant,
      mdiSend,
      mdiShare,
      mdiStepForward,
      mdiTable,
      mdiTextBoxEditOutline,
      mdiTwitter,
      mdiFolderInformationOutline,
      mdiFileMultipleOutline
    }
  },
  theme: {
    dark: false,
    themes: {
      light: {
        primary: '#58539e',
        secondary: '#f39506',
        // Following colors are from the MUI default dark palette
        // https://mui.com/customization/palette/#default-values
        info: '#0288d1',
        warning: '#f57c00',
        error: '#d32f2f',
        success: '#388e3c'
      }
    }
  }
}
