PREFIX h: <http://hestia.ai/>

SELECT ?advertiserName ?targetingType ?targetingValue (COUNT(?criterion) AS ?count) WHERE
{
  {
    SELECT ?advertiserName (COUNT(?impression) AS ?countImpressions) WHERE 
    {
      ?impression a h:Impression .
      ?impression h:advertiserName ?advertiserName .
    }
    GROUP BY ?advertiserName
    ORDER BY DESC(?countImpressions)
    LIMIT 10
  }
  ?criterion a h:Criterion .
  ?criterion h:advertiserName ?advertiserName .
  ?criterion h:targetingType ?targetingType .
  ?criterion h:targetingValue ?targetingValue .
}
GROUP BY ?advertiserName ?targetingType ?targetingValue
