# authors: Valentin Oliver Loftsson <valentin@hestia.ai>
PREFIX :   <http://schema.org/>
PREFIX ex: <http://www.example.com/>

SELECT ?year ?advertiserName (COUNT(?imp) AS ?count)
WHERE {
    ?imp a :AdvertiserContentArticle .
    ?imp :creator ?advertiser .
    ?advertiser :name ?advertiserName .
    ?imp :contentReferenceTime ?d
    BIND(year(?d) AS ?year)
}
GROUP BY ?year ?advertiserName
ORDER BY DESC(?year) DESC(?count)
